build:
  image: stormenroute/storm-enroute-build:0.4
  environment:
    - SSH_KEY_PASS=$$SSH_KEY_PASS
    - SONATYPE_USER=$$SONATYPE_USER
    - SONATYPE_PASS=$$SONATYPE_PASS
  commands:
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - eval `ssh-agent -s`
    - |
      if [ ! -z $SSH_KEY_PASS ]; then
        export DISPLAY=""
        echo "executed if!!"
      fi
    - echo "pull request no. $DRONE_PULL_REQUEST"
    - if [ "$DRONE_PULL_REQUEST" != "" ]; then (sbt test); else (sbt mecha-nightly); fi
