build:
  image: stormenroute/storm-enroute-build:0.4
  environment:
    - SSH_KEY_PASS=$${SSH_KEY_PASS=""}
    - SONATYPE_USER=$${SONATYPE_USER=""}
    - SONATYPE_PASS=$${SONATYPE_PASS=""}
  commands:
    - echo $$TEST_SECRET
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - |
      if [ -n $SSH_KEY_PASS ]; then
        eval `ssh-agent -s`
        echo "Setting up ssh-agent."
        echo "exec cat" > ap-cat.sh
        chmod a+x ap-cat.sh
        export DISPLAY=1
        echo $SSH_KEY_PASS | SSH_ASKPASS=./ap-cat.sh ssh-add ~/.ssh/id_rsa
        rm ap-cat.sh
        export SSH_KEY_PASS=""
        export DISPLAY=""
      fi
    - echo "pull request no. $DRONE_PULL_REQUEST"
    - if [ "$DRONE_PULL_REQUEST" != "" ]; then (sbt test); else (sbt mecha-nightly); fi
